apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-pv # Nombre del PersistentVolume, modificar según sea necesario
spec:
  capacity:
    storage: 1Gi # Capacidad de almacenamiento del volumen, ajustar según requisitos
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" # Ruta en el nodo donde se almacenarán los datos, modificar según sea necesario
